### ISSUE TITLE
FileNotFoundError: 'metrics/lpips/weights/v0.1/alex.pth'

### ISSUE THREAD

**Issue by LokiXun** [danier97/LDMVFI#1]
Hi, It seems like missing the LPIP model's weight which raise error when I run the following command
```
python evaluate.py \
        --config configs/ldm/ldmvfi-vqflow-f32-c256-concat_max.yaml \
        --ckpt checkpoints/ldmvfi-vqflow-f32-c256-concat_max.ckpt \
        --dataset Middlebury_others \
        --metrics PSNR SSIM LPIPS \
        --data_dir /home/ps/Desktop/dataset \
        --out_dir eval_results/ldmvfi-vqflow-f32-c256-concat_max/ \
        --use_ddim
```

The error located at `metrics/lpips/lpips.py` Line 80, which load the model from local but there isn't one. 
```            if(pretrained):
                if(model_path is None):
                    import inspect
                    import os
                    model_path = os.path.abspath(os.path.join(inspect.getfile(self.__init__), '..', 'weights/v%s/%s.pth'%(version,net)))

                if(verbose):
                    print('Loading model from: %s'%model_path)
                self.load_state_dict(torch.load(model_path, map_location='cpu'), strict=False)   
```

Is there any special for the missed alexnet model? It confuses me cause I saw Line 57 in `metrics/lpips/lpips.py` already load the model from `torchvision` package

**Comment by danier97** [comment]
Hi,

The LPIPS code is copied from the original repo [here](https://github.com/richzhang/PerceptualSimilarity). You can find the LPIPS checkpoint file from [here](https://github.com/richzhang/PerceptualSimilarity/blob/master/lpips/weights/v0.1/alex.pth). Make sure you place it in the directory specifed on line 76 (or modify line 76 to point to where you store the `.pth` file).

While line 57 indeed loads the weights for the feature extractor, LPIPS contains several extra linear layers to predict the perceptual distance, so their weights must also be loaded.

I hope this helps.

Thanks.

**Comment by LokiXun** [comment]
Got it, Thanks!
