### ISSUE TITLE
Davis Testset?

### ISSUE THREAD

**Issue by JHLew** [danier97/LDMVFI#11]
Hi, thank you for sharing your work to the public.
I was trying to setup my evaluation setting with the Davis dataset, having your implementation as a reference, and I figured that in your implementation, there seems to be 2 dataloaders named Davis. one named "Davis" and another named "Davis90_triplet".

I assume that "Davis90_triplet" is the correct one used for evaluations of the paper, would that be right?
May I ask what would the other Davis loader be...?

**Comment by JHLew** [comment]
For clarification, I'm confused with which sets and frames I should use.
The "Davis" loader seems like it has specifically chosen sequences, while my expectation was to use the entire sequences / all frames of the davis-90 set, as in "Davis90_triplet".

Is using all sequences with "Davis90_triplet" the one?

**Comment by danier97** [comment]
Hi,

Sorry for the delayed response! Yes you are right, the `Davis_triplet` should be the correct one to use, which uses all frame triplets from the 90 sequences from [here](https://sites.google.com/view/xiangyuxu/qvi_nips19) for evaluation. The other class `Davis` is from an older code used for debugging.

Thanks.
