### ISSUE TITLE
interpolate_yuv.py error

### ISSUE THREAD

**Issue by ButoneDream** [danier97/LDMVFI#12]
Traceback (most recent call last):
  File "/data/zhoulei/Project/LDMVFI/interpolate_yuv.py", line 129, in <module>
    main()
  File "/data/zhoulei/Project/LDMVFI/interpolate_yuv.py", line 115, in main
    writer.writeFrame(tensor2rgb(frame0)[0])
  File "/data/zhoulei/anaconda3/envs/ldmvfi/lib/python3.9/site-packages/skvideo/io/abstract.py", line 519, in writeFrame
    raise IOError(msg)
OSError: [Errno 32] Broken pipe

FFMPEG COMMAND:
/data/zhoulei/anaconda3/envs/ldmvfi/bin/ffmpeg -y -r 60 -f rawvideo -pix_fmt rgb24 -s 1024x1024 -i - -pix_fmt yuv420p -s 1024x1024 -r 60 -vcodec libx264 -crf 0 -preset veryslow /data/zhoulei/Project/LDMVFI/result/p_1024x1024_60fps_LDMVFI.mp4

FFMPEG STDERR OUTPUT:

**could you give me some idea?** the img_size in p.yuv is 1024*1024 
——————————————
i use the command below:
```
python interpolate_yuv.py \
--net LDMVFI \
--config configs/ldm/ldmvfi-vqflow-f32-c256-concat_max.yaml \
--ckpt ckpt/ldmvfi-vqflow-f32-c256-concat_max.ckpt \
--input_yuv p.yuv \
--size 1024x1024 \
--out_fps 60 \
--out_dir result \
`--use_ddim`
```
————————————
![image](https://github.com/danier97/LDMVFI/assets/98502973/6c3020f1-0735-42a2-95b3-0dac57267e0c)

**Comment by danier97** [comment]
Hi,

Sorry about the issue, but I've never encountered this and based on your screenshot the python control code seems to be working fine. 

I saw the same issue discussed and a solution shared [here](https://github.com/royorel/StyleSDF/issues/20#issuecomment-1768323024). Please let me know if this resolves the problem.

Thank you.

**Comment by ButoneDream** [comment]
thanks！it is useful! 
and the  solution is to replace the ffmpeg file under the ~/Environment/anaconda3/envs/pytorch3d/bin/ with the file ffmpeg downloaded from https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz.
