### ISSUE TITLE
trainer error

### ISSUE THREAD

**Issue by bo-wang-up** [danier97/LDMVFI#16]
When I run the training code "python main.py --base configs/autoencoder/vqflow-f32.yaml -t --gpus 0", the error appears:

Traceback (most recent call last):
  File "/home/codes/LDMVFI/main.py", line 730, in <module>
    if trainer.global_rank == 0:
NameError: name 'trainer' is not defined

**Comment by danier97** [comment]
Hi,

Looks like something's gone wrong in the `try` statement before `trainer` is defined (i.e. between line 487 and 643). You might want to take a look at the full error log to find out what caused an exception.

Thanks.

**Comment by bo-wang-up** [comment]
I replace "trainer.global_rank==0" with "Trainer.global_rank==0" . The method seems effective.
