### ISSUE TITLE
Training error in loading the samples in vimep)setuplet

### ISSUE THREAD

**Issue by bo-wang-up** [danier97/LDMVFI#17]
when I run the training code "python main.py --base configs/autoencoder/vqflow-f32.yaml -t --gpus 0", the error appears "FileNotFoundError: [Errno 2] No such file or directory: 'data/vimeo_septuplet/sequences/00001/0389/im4.png'". 

I noticed that my downloaded Vimeo image files are named image1, image2, and image3, while you use the names image3, image4, and image5. 
Does this difference in naming have any special implications? 
Do I need to rename my files from image1, image2, and image3 to image3, image4, and image5?

Thanks for your help!

**Comment by zijieloooooou** [comment]
I encountered the same problem, how did you solve it? Thanks！
