### ISSUE TITLE
Which split was used for DAVIS?

### ISSUE THREAD

**Issue by basilevh** [danier97/LDMVFI#2]
The readme states:
```
    ├──── davis90/
    |   ├──── bear/
    |   ├──── ...
    |   └──── walking/
```
but if `bear` and `walking` are the first and last entry respectively then the best match I can find is the DAVIS 2017 train split, not val?  Any insight would be appreciated, thanks!

**Comment by basilevh** [comment]
Ok actually it looks like no splits were used and all the videos were included instead. Would you mind confirming this is correct please? Thanks again in advance!

**Comment by danier97** [comment]
Hi, sorry for the late reply. 

The Davis90 test set used here can be downloaded from [here](https://www.dropbox.com/s/9t6x7fi9ui0x6bt/davis-90.zip?dl=0), and this is provided by the authors of the [QVI paper](https://sites.google.com/view/xiangyuxu/qvi_nips19). I didn't check if this fully matches the DAVIS-17 splits.

Thanks.
