### ISSUE TITLE
Pretrained model for autoencoder

### ISSUE THREAD

**Issue by Ren-creater** [danier97/LDMVFI#4]
Hi!

It seems like you have only uploaded the pretrained model for the denoising UNet. Could you please provide the pretrained model for the autoencoder (VQ-FIGAN)? Thank you.

**Comment by danier97** [comment]
Hi!

The checkpoint I uploaded actually contains the weights of both the autoencoder and the UNet. 

If you load the checkpoint file (using `torch.load()`) and check the keys of the `state_dict`, you can see the parameters of the autoencoder (i.e. `first_state_model.*`) are also there.

I hope this helps.

Thanks.
