### ISSUE TITLE
VFIPS

### ISSUE THREAD

**Issue by basilevh** [danier97/LDMVFI#5]
Hi,
I'm having some trouble obtaining reasonable outputs for the [VFIPS](https://github.com/hqqxyy/VFIPS) metric in my project. I noticed that this repository has evaluation code for FloLPIPS but not VFIPS. Is there any chance you could upload the VFIPS evaluation code as well as a reference to ensure consistent, fair comparisons?
Thanks in advance!

**Comment by danier97** [comment]
Hi,

There was something wrong in my VFIPS evaluation code, so the VFIPS results in the old arxiv version of the paper are unreliable. Therefore I removed those results and updated the arxiv version. I haven't got time to debug and do full VFIPS evaluations as I'm working on other projects, so I'm afraid I don't have useful VFIPS evaluation code to share. 

Apologies for the inconvenience!

Thanks.

**Comment by basilevh** [comment]
Hi,
No worries at all and I do appreciate the update and honesty! This information definitely helps. Do you remember by any chance what went wrong? Was it some kind of bug in their model? (I did notice for example that my numbers are always closer to -100 than to +100, but I don't quite know if simply flipping the sign is the correct solution, as I feel like this behavior possibly indicates a deeper issue.) I might try to look into it to see if I can get it right for my project (also given, of course, a finite budget of time and effort), so any pointer helps. Thanks a lot again!

**Comment by danier97** [comment]
Hi,

Sorry I missed your message! I am not sure what exactly was wrong but I couldn't get consistent results. There might have been bugs in my VFIPS evaluation/experiment code. I also remember obtaining large negative values for VFIPS which I was suspicious about but didn't dig deeper. 

Thanks.
