### ISSUE TITLE
Global Step key missing from checkpoint

### ISSUE THREAD

**Issue by Ber1812** [danier97/LDMVFI#7]
Hi, thank you very much for the interesting work!
I am trying to fine tune the model on my own dataset, however the checkpoint for the pre-trained model seems to be missing a global step key. This is the error I got:
batch_loop.optimizer_loop.optim_progress.optimizer.step.total.completed = self._loaded_checkpoint[
KeyError: 'global_step'
I  am using pytorch version==2.0.0.post200 and pytorch-lightning== 1.7.7

**Comment by danier97** [comment]
Hi,

Thank you for your interest in the work! If you used the `--resume` argument and specified the checkpoint path, then the code will try to load all the training related stuff such as `global_step`, `optimizer_state`, etc. These are specific to the pre-training dataset, and in my opinion they are not helpful for finetuning on other datasets (please correct me if I'm wrong).

Alternatively, you could simply load the pre-trained weights as soon as you instantiate the model (without using the `--resume` option), by e.g. doing the following on line [567](https://github.com/danier97/LDMVFI/blob/eee2dc3566f21f22787d66b0f0337e48318403c6/main.py#L514) of `main.py`:

```python
model = instantiate_from_config(config.model)
pt_ckpt = torch.load('<path/to/pretrained/ckpt>')
model.load_state_dict(pt_ckpt['state_dict'])
```

Please let me know if this makes sense.

Thanks.
