### ISSUE TITLE
Dataset problems: failed to unzip bvidvc.zip

### ISSUE THREAD

**Issue by ZerinHwang03** [danier97/LDMVFI#8]
Thank you so much for the amazing work!

When I unzip the bvidvc.zip from [BVI-DVC quintuplets](https://drive.google.com/file/d/1i_CoqiNrZ2AU8DKjU8aHM1jIaDGW0fE5/view?usp=sharing), I got these errors:

>ERRORS:
Headers Error
Unconfirmed start of archive
WARNINGS:
There are data after the end of archive
--
Path = bvidvc.zip
Type = zip
ERRORS:
Headers Error
Unconfirmed start of archive
WARNINGS:
There are data after the end of archive
Physical Size = 6481384309
Tail Size = 4616
ERROR: CRC Failed : bvidvc/quintuplets.zip

Can you suggest what to do?

**Comment by shanshuo** [comment]
+1

**Comment by gitlabspy** [comment]
How do you solved this?

**Comment by ZXMMD** [comment]
+1

**Comment by zijieloooooou** [comment]
> How do you solved this?
you can try:
zip -FF bvidvc.zip --out fixed.zip -fz
