### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'iter'

### ISSUE THREAD

**Issue by Iceeteeea** [danier97/LDMVFI#9]
Hi, thank you very much for the interesting work!
I want to train the model, but something error. 
`Traceback (most recent call last):
  File "/workspace/LDMVFI/main.py", line 652, in <module>
    data.prepare_data()
  File "/workspace/LDMVFI/main.py", line 180, in prepare_data
    instantiate_from_config(data_cfg)
  File "/workspace/LDMVFI/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
TypeError: __init__() got an unexpected keyword argument 'iter'`

**Comment by danier97** [comment]
Hi, thank you for your interest in our work!

It seems like you've changed the training dataset in the config (i.e. the `data.params.train.target` [field](https://github.com/danier97/LDMVFI/blob/eee2dc3566f21f22787d66b0f0337e48318403c6/configs/ldm/ldmvfi-vqflow-f32-c256-concat_max.yaml#L70)), but left the [old keyword arguments](https://github.com/danier97/LDMVFI/blob/eee2dc3566f21f22787d66b0f0337e48318403c6/configs/ldm/ldmvfi-vqflow-f32-c256-concat_max.yaml#L71) unchanged (which includes the argument `iter`). 

In the config file (`.yaml`), you need to make sure the `params` field of `data.params.train` match the arguments for the dataset class specified in `data.params.train.target`.

I hope this helps.

Thanks.

**Comment by Iceeteeea** [comment]
Thanks！it works.
